# Generated by Django 4.1.3 on 2022-12-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
