# Generated by Django 4.1.3 on 2022-12-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_alter_portafolio_descripcion_alter_portafolio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='foto',
            field=models.URLField(max_length=100),
        ),
    ]
